@startuml

'https://plantuml.com/component-diagram

skinparam componentStyle rectangle
package "Program Logic" {
  [Main()]
}

() ObjectOutputStream

folder "Save" {
  frame [Data]

}


[Main()] <..> [ObjectOutputStream]
[ObjectOutputStream] <..> [Data]

@enduml