@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor Пользователь
participant Main
participant Person
Collections Training

Пользователь -> Main: Start

Пользователь -> Main: Select Person
Main -> Person: Create/Load Person
Main <-- Person: Person
Пользователь -> Main: Start Training
Пользователь -> Main: Select Training type

Main -> Training: Create Training
Main <--Training: training
Пользователь-> Main: Start stopwatch
Пользователь -> Main: Stop stopwatch
Main -> Main: Calculate the duration
Main -> Training: Set duration
Main <-- Training: durationTraining


Main -> Person: Add Training
Пользователь -> Main: See Training
Main ->Person: See Training

Person -> Training: Get Name
Training --> Person: trainingName
Person -> Training: Get Time
Training --> Person: durationTraining
Person -> Training: Get Calories
Training --> Person: trainingCalories
Person --> Пользователь: Table of Training


Пользователь ->Main: Save
Main ->Main: Save

@enduml